### ISSUE TITLE
Feature Request: Download Organization List as JSON or CSV

### ISSUE THREAD

**Issue by quinn-p-mchugh** [veganhacktivists/animalrightsmap#11]
Hey all, love the map. Thank you for creating it!

Is there a way to download the organization data displayed as JSON or CSV?

I'm doing some outreach work for [Open Paws](https://openpaws.ai) and having this data available in a structured format would help streamline our efforts.

I suspect others would find this useful as well.

**Comment by stephan281094** [comment]
Hi Quinn,  thank you for your interest!

It's possible to download the GeoJson or CSV using the "Share and download"-button. This will get you _all_ data that's being displayed on the map, see:
![Screenshot 2024-05-21 at 12 17 12](https://github.com/veganhacktivists/animalrightsmap/assets/4006802/f9ca2034-6485-4719-91ed-fa47cad04f4a)

Let me know if that answers your question! 🐥

**Comment by quinn-p-mchugh** [comment]
Hi Stephan, thanks for the prompt reply!

My apologies - I totally missed that tab.

This is exactly what I was looking for. Thank you so much!
